development:
    login: sell_1342421142_biz_api1.gmail.com
    password: 1342421182
    signature: AFcWxV21C7fd0v3bYYYRCpSSRl31AmYTMnOXJuR64BeQRmX.k-qC1-OP
    paypal_email: sell_1342421142_biz@gmail.com
    paypal_url: https://www.sandbox.paypal.com/cgi-bin/webscr

test:
    paypal_email: test@example.com
    paypal_url: testpaypalurl

production:
    login: copy-the-email-here
    password: password-goes-here
    signature: signature-goes-here
    paypal_email: seller@example.com
    paypal_url: https://www.paypal.com/cgi-bin/webscr